const FETCH_LAWYERS_INIT = "FETCH_LAWYERS_INIT";
const FETCH_LAWYERS_SUCCESS = "FETCH_LAWYERS_SUCCESS";
const FETCH_LAWYERS_FAILURE = "FETCH_LAWYERS_FAILURE";
const DATA_REORDER_DRAGG = "DATA_REORDER_DRAGG";
export {
	FETCH_LAWYERS_FAILURE,
	FETCH_LAWYERS_INIT,
	FETCH_LAWYERS_SUCCESS,
	DATA_REORDER_DRAGG,
};
