const FETCH_LAWYERS_INIT = "FETCH_LAWYERS_INIT";
const FETCH_LAWYERS_SUCCESS = "FETCH_LAWYERS_SUCCESS";
const FETCH_LAWYERS_FAILURE = "FETCH_LAWYERS_FAILURE";

export { FETCH_LAWYERS_FAILURE, FETCH_LAWYERS_INIT, FETCH_LAWYERS_SUCCESS };
